/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SocialScriptQuery {
    topic: string;
    content: string;
    hashtags: string;
    hooks: string;
    body: string;
    tone: Tone;
    platform: SocialMediaPlatform;
    callToAction: string;
    timestamp: bigint;
}
export interface AdminKeys {
    groqKey: string;
    geminiKey: string;
}
export enum SocialMediaPlatform {
    linkedin = "linkedin",
    tiktok = "tiktok",
    instagram = "instagram",
    youtube = "youtube"
}
export enum Tone {
    funny = "funny",
    hype = "hype",
    professional = "professional"
}
export interface backendInterface {
    generateScript(platform: SocialMediaPlatform, topic: string, tone: Tone): Promise<string>;
    getAdminKeys(): Promise<AdminKeys | null>;
    getScriptHistory(): Promise<Array<SocialScriptQuery>>;
    getScriptHistoryForCreator(): Promise<Array<string>>;
    getScriptsByPlatform(platform: SocialMediaPlatform): Promise<Array<string>>;
    getScriptsByPlatformAndTone(platform: SocialMediaPlatform, tone: Tone): Promise<Array<string>>;
    setAdminKeys(geminiKey: string, groqKey: string): Promise<void>;
}
import type { AdminKeys as _AdminKeys, SocialMediaPlatform as _SocialMediaPlatform, SocialScriptQuery as _SocialScriptQuery, Tone as _Tone } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async generateScript(arg0: SocialMediaPlatform, arg1: string, arg2: Tone): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateScript(to_candid_SocialMediaPlatform_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Tone_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateScript(to_candid_SocialMediaPlatform_n1(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_Tone_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAdminKeys(): Promise<AdminKeys | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminKeys();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminKeys();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScriptHistory(): Promise<Array<SocialScriptQuery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptHistory();
                return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptHistory();
            return from_candid_vec_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getScriptHistoryForCreator(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptHistoryForCreator();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptHistoryForCreator();
            return result;
        }
    }
    async getScriptsByPlatform(arg0: SocialMediaPlatform): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptsByPlatform(to_candid_SocialMediaPlatform_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptsByPlatform(to_candid_SocialMediaPlatform_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getScriptsByPlatformAndTone(arg0: SocialMediaPlatform, arg1: Tone): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getScriptsByPlatformAndTone(to_candid_SocialMediaPlatform_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tone_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getScriptsByPlatformAndTone(to_candid_SocialMediaPlatform_n1(this._uploadFile, this._downloadFile, arg0), to_candid_Tone_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setAdminKeys(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdminKeys(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdminKeys(arg0, arg1);
            return result;
        }
    }
}
function from_candid_SocialMediaPlatform_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialMediaPlatform): SocialMediaPlatform {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_SocialScriptQuery_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SocialScriptQuery): SocialScriptQuery {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Tone_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Tone): Tone {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminKeys]): AdminKeys | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    content: string;
    hashtags: string;
    hooks: string;
    body: string;
    tone: _Tone;
    platform: _SocialMediaPlatform;
    callToAction: string;
    timestamp: bigint;
}): {
    topic: string;
    content: string;
    hashtags: string;
    hooks: string;
    body: string;
    tone: Tone;
    platform: SocialMediaPlatform;
    callToAction: string;
    timestamp: bigint;
} {
    return {
        topic: value.topic,
        content: value.content,
        hashtags: value.hashtags,
        hooks: value.hooks,
        body: value.body,
        tone: from_candid_Tone_n9(_uploadFile, _downloadFile, value.tone),
        platform: from_candid_SocialMediaPlatform_n11(_uploadFile, _downloadFile, value.platform),
        callToAction: value.callToAction,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    funny: null;
} | {
    hype: null;
} | {
    professional: null;
}): Tone {
    return "funny" in value ? Tone.funny : "hype" in value ? Tone.hype : "professional" in value ? Tone.professional : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    linkedin: null;
} | {
    tiktok: null;
} | {
    instagram: null;
} | {
    youtube: null;
}): SocialMediaPlatform {
    return "linkedin" in value ? SocialMediaPlatform.linkedin : "tiktok" in value ? SocialMediaPlatform.tiktok : "instagram" in value ? SocialMediaPlatform.instagram : "youtube" in value ? SocialMediaPlatform.youtube : value;
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SocialScriptQuery>): Array<SocialScriptQuery> {
    return value.map((x)=>from_candid_SocialScriptQuery_n7(_uploadFile, _downloadFile, x));
}
function to_candid_SocialMediaPlatform_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaPlatform): _SocialMediaPlatform {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Tone_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tone): _Tone {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SocialMediaPlatform): {
    linkedin: null;
} | {
    tiktok: null;
} | {
    instagram: null;
} | {
    youtube: null;
} {
    return value == SocialMediaPlatform.linkedin ? {
        linkedin: null
    } : value == SocialMediaPlatform.tiktok ? {
        tiktok: null
    } : value == SocialMediaPlatform.instagram ? {
        instagram: null
    } : value == SocialMediaPlatform.youtube ? {
        youtube: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Tone): {
    funny: null;
} | {
    hype: null;
} | {
    professional: null;
} {
    return value == Tone.funny ? {
        funny: null
    } : value == Tone.hype ? {
        hype: null
    } : value == Tone.professional ? {
        professional: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
