/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminKeys { 'groqKey' : string, 'geminiKey' : string }
export type SocialMediaPlatform = { 'linkedin' : null } |
  { 'tiktok' : null } |
  { 'instagram' : null } |
  { 'youtube' : null };
export interface SocialScriptQuery {
  'topic' : string,
  'content' : string,
  'hashtags' : string,
  'hooks' : string,
  'body' : string,
  'tone' : Tone,
  'platform' : SocialMediaPlatform,
  'callToAction' : string,
  'timestamp' : bigint,
}
export type Tone = { 'funny' : null } |
  { 'hype' : null } |
  { 'professional' : null };
export interface _SERVICE {
  'generateScript' : ActorMethod<[SocialMediaPlatform, string, Tone], string>,
  'getAdminKeys' : ActorMethod<[], [] | [AdminKeys]>,
  'getScriptHistory' : ActorMethod<[], Array<SocialScriptQuery>>,
  'getScriptHistoryForCreator' : ActorMethod<[], Array<string>>,
  'getScriptsByPlatform' : ActorMethod<[SocialMediaPlatform], Array<string>>,
  'getScriptsByPlatformAndTone' : ActorMethod<
    [SocialMediaPlatform, Tone],
    Array<string>
  >,
  'setAdminKeys' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];