/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SocialMediaPlatform = IDL.Variant({
  'linkedin' : IDL.Null,
  'tiktok' : IDL.Null,
  'instagram' : IDL.Null,
  'youtube' : IDL.Null,
});
export const Tone = IDL.Variant({
  'funny' : IDL.Null,
  'hype' : IDL.Null,
  'professional' : IDL.Null,
});
export const AdminKeys = IDL.Record({
  'groqKey' : IDL.Text,
  'geminiKey' : IDL.Text,
});
export const SocialScriptQuery = IDL.Record({
  'topic' : IDL.Text,
  'content' : IDL.Text,
  'hashtags' : IDL.Text,
  'hooks' : IDL.Text,
  'body' : IDL.Text,
  'tone' : Tone,
  'platform' : SocialMediaPlatform,
  'callToAction' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'generateScript' : IDL.Func(
      [SocialMediaPlatform, IDL.Text, Tone],
      [IDL.Text],
      [],
    ),
  'getAdminKeys' : IDL.Func([], [IDL.Opt(AdminKeys)], ['query']),
  'getScriptHistory' : IDL.Func([], [IDL.Vec(SocialScriptQuery)], ['query']),
  'getScriptHistoryForCreator' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getScriptsByPlatform' : IDL.Func(
      [SocialMediaPlatform],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getScriptsByPlatformAndTone' : IDL.Func(
      [SocialMediaPlatform, Tone],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'setAdminKeys' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SocialMediaPlatform = IDL.Variant({
    'linkedin' : IDL.Null,
    'tiktok' : IDL.Null,
    'instagram' : IDL.Null,
    'youtube' : IDL.Null,
  });
  const Tone = IDL.Variant({
    'funny' : IDL.Null,
    'hype' : IDL.Null,
    'professional' : IDL.Null,
  });
  const AdminKeys = IDL.Record({
    'groqKey' : IDL.Text,
    'geminiKey' : IDL.Text,
  });
  const SocialScriptQuery = IDL.Record({
    'topic' : IDL.Text,
    'content' : IDL.Text,
    'hashtags' : IDL.Text,
    'hooks' : IDL.Text,
    'body' : IDL.Text,
    'tone' : Tone,
    'platform' : SocialMediaPlatform,
    'callToAction' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'generateScript' : IDL.Func(
        [SocialMediaPlatform, IDL.Text, Tone],
        [IDL.Text],
        [],
      ),
    'getAdminKeys' : IDL.Func([], [IDL.Opt(AdminKeys)], ['query']),
    'getScriptHistory' : IDL.Func([], [IDL.Vec(SocialScriptQuery)], ['query']),
    'getScriptHistoryForCreator' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getScriptsByPlatform' : IDL.Func(
        [SocialMediaPlatform],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getScriptsByPlatformAndTone' : IDL.Func(
        [SocialMediaPlatform, Tone],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'setAdminKeys' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };